plugins:
	-jekyll-relative-links
relative_links:
	enabled: true
	collections: true
include:
	index.md
	README.md
	README_ES.md
	Implementation.md
	Implementation_ES.md
	Method.md
	Method_ES.md
